{% set name = "sqlalchemy" %}
{% set version = "2.0.2" %}

package:
  name: sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SQLAlchemy-{{ version }}.tar.gz
  sha256: e4d3cf5352f724237e27463de4bf19888235342af2efa37ef1cd391d8b702a16

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - greenlet !=0.4.17
    - typing-extensions >=4.2.0

test:
  requires:
    - pip
  imports:
    - sqlalchemy
  commands:
    - pip check

about:
  home: https://www.sqlalchemy.org/
  license: MIT
  license_file: LICENSE
  summary: Database Abstraction Library.
  description: |
    SQLAlchemy is the Python SQL toolkit and Object Relational Mapper that
    gives application developers the full power and flexibility of SQL.
  doc_url: https://docs.sqlalchemy.org/
  dev_url: https://github.com/sqlalchemy/sqlalchemy
  doc_source_url: https://github.com/zzzeek/sqlalchemy/blob/master/doc/build/index.rst

extra:
  recipe-maintainers:
    - xylar
    - ocefpaf
    - mcs07
    - nehaljwani
    - igortg
